export const GET_MY_DEVICES_REQUEST = "GET_MY_DEVICES_REQUEST";
export const GET_MY_DEVICES_SUCCESS = "GET_MY_DEVICES_SUCCESS";
export const GET_MY_DEVICES_FAILURE = "GET_MY_DEVICES_FAILURE";
export const CLEAR_MY_DEVICES = "CLEAR_MY_DEVICES";

export const ADD_NEW_DEVICE_REQUEST = "ADD_NEW_DEVICE_REQUEST";
export const ADD_NEW_DEVICE_SUCCESS = "ADD_NEW_DEVICE_SUCCESS";
export const ADD_NEW_DEVICE_FAILURE = "ADD_NEW_DEVICE_FAILURE";

export const GET_DEVICE_REQUEST = "GET_DEVICE_REQUEST";
export const GET_DEVICE_SUCCESS = "GET_DEVICE_SUCCESS";
export const GET_DEVICE_FAILURE = "GET_DEVICE_FAILURE";

export const UPDATE_DEVICE_REQUEST = "UPDATE_DEVICE_REQUEST";
export const UPDATE_DEVICE_SUCCESS = "UPDATE_DEVICE_SUCCESS";
export const UPDATE_DEVICE_FAILURE = "UPDATE_DEVICE_FAILURE";
export const DEVICE_RESET = "DEVICE_RESET";

export const DELETE_DEVICE_REQUEST = "DELETE_DEVICE_REQUEST";
export const DELETE_DEVICE_SUCCESS = "DELETE_DEVICE_SUCCESS";
export const DELETE_DEVICE_FAILURE = "DELETE_DEVICE_FAILURE";

export const FILTER_DEVICES = "FILTER_DEVICES";
export const SEARCH_DEVICES = "SEARCH_DEVICES";
export const SORT_DEVICES = "SORT_DEVICES";
export const RESET_DEVICES = "RESET_DEVICES";

export const SET_DEVICE_FILTERS = "SET_DEVICE_FILTERS";
export const SET_CHART_FILTERS = "SET_CHART_FILTERS";

export const GET_PM2_5_PAST_24_HOURS_REQUEST = "GET_PM2_5_PAST_24_HOURS_REQUEST";
export const GET_PM2_5_PAST_24_HOURS_SUCCESS = "GET_PM2_5_PAST_24_HOURS_SUCCESS";
export const GET_PM2_5_PAST_24_HOURS_FAILURE = "GET_PM2_5_PAST_24_HOURS_FAILURE";

export const GET_DASHBOARD_CHART_DATA_REQUEST = "GET_DASHBOARD_CHART_DATA_REQUEST";
export const GET_INITIAL_DASHBOARD_CHART_DATA_REQUEST = "GET_INITIAL_DASHBOARD_CHART_DATA_REQUEST";
export const GET_DASHBOARD_CHART_DATA_SUCCESS = "GET_DASHBOARD_CHART_DATA_SUCCESS";
export const GET_DASHBOARD_CHART_DATA_FAILURE = "GET_DASHBOARD_CHART_DATA_FAILURE";

export const GET_SCHEMA_REQUEST = "GET_SCHEMA_REQUEST";
export const GET_SCHEMA_SUCCESS = "GET_SCHEMA_SUCCESS";
export const GET_SCHEMA_FAILURE = "GET_SCHEMA_FAILURE";

export const SET_ALL_CHART_FILTERS_REQUEST = "SET_ALL_CHART_FILTERS_REQUEST";
export const SET_ALL_CHART_FILTERS_SUCCESS = "SET_ALL_CHART_FILTERS_SUCCESS";